list(APPEND PCB_ListTargetLinkLibs
#    winmm.lib
#    kernel32.lib
#    user32.lib
#    gdi32.lib
#    winspool.lib
#    comctl32.lib
#    comdlg32.lib
#    advapi32.lib
#    shell32.lib
#    ole32.lib
#    oleaut32.lib
#    uuid.lib
#    odbc32.lib
#    odbccp32.lib
#    netapi32.lib
#    #libmsvcrtd.lib
#    msvcrt.lib
#    #libubsan.dll.lib
#    ws2_32.lib
)
