..\..\..\Tools\Gfx\BmpRplc Icons01_16x16.Bmp 0xffffff 0xffff00 Icons01_16x16_1BPP_1G.Bmp
..\..\..\Tools\Gfx\BmpRplc Icons01_16x16_1BPP_1G.Bmp 0x000000 0xffffff Icons01_16x16_1BPP_1G.Bmp
..\..\..\Tools\Gfx\BmpRplc Icons01_16x16_1BPP_1G.Bmp 0xffff00 0x000000 Icons01_16x16_1BPP_1G.Bmp
..\..\..\Tools\Gfx\BmpTres Icons01_16x16_1BPP_1G.Bmp 0xffffff Icons01_16x16_1BPP_1G.Bmp
..\..\..\Tools\Gfx\RasterScan 19 13 16 16 0 Icons01_16x16_1BPP_1G.Bmp